[Setup]
AppName=BliemBoard
AppVersion=2.0.0
DefaultDirName={autopf}\BliemBoard
DefaultGroupName=BliemBoard
OutputDir=dist-installer
OutputBaseFilename=BliemBoard_Setup
SetupIconFile=src-tauri\icons\icon.ico
UninstallDisplayIcon={app}\BliemBoard.exe
Compression=lzma2
SolidCompression=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=lowest

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startup"; Description: "Start BliemBoard when Windows starts"; GroupDescription: "AutoStart Options";

[Files]
; The executable generated by 'npm run tauri build'
Source: "src-tauri\target\release\soundboard-tauri.exe"; DestDir: "{app}"; DestName: "BliemBoard.exe"; Flags: ignoreversion

[Icons]
Name: "{group}\BliemBoard"; Filename: "{app}\BliemBoard.exe"
Name: "{autodesktop}\BliemBoard"; Filename: "{app}\BliemBoard.exe"; Tasks: desktopicon

[Registry]
; Add a startup registry key if the user selected the "startup" task
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "BliemBoard"; ValueData: """{app}\BliemBoard.exe"" --minimized"; Flags: uninsdeletevalue; Tasks: startup

[Run]
Filename: "{app}\BliemBoard.exe"; Description: "{cm:LaunchProgram,BliemBoard}"; Flags: nowait postinstall skipifsilent
